bsg:
    config:
        path: /home/david/code/reference4j/src/main/resources/secret.json
spring:
    main:
        banner:
            location: classpath:banner.txt
        allow-bean-definition-overriding: true
    datasource:
        maximum-pool-size: 2
logging:
    level:
        org:
            apache:
                kafka: WARN
            springframework:
                kafka: WARN
kafka:
    consumer_group: demo
    enable_auto_commit: false
    consumer: demo-consumer
    producer: demo-producer
    topic:
        iLookB4DrinkJava: iLookB4DrinkJava

springdoc:
    api-docs:
        path: /api-docs
